#!/bin/sh

if [ -n "$APPVEYOR_BUILD_FOLDER" ]; then
	cd $APPVEYOR_BUILD_FOLDER
fi

for repo in devops test-data; do
	git clone https://github.com/project-renard/$repo.git  external/project-renard/$repo || return $?
done
. external/project-renard/devops/ENV.sh
