#!/bin/sh

if [ "$TRAVIS_OS_NAME" == "osx" ]; then
	brew update || return $?
	brew tap Caskroom/cask || return $?
	brew install Caskroom/cask/xquartz || return $?
	( sed 's/#.*//' < homebrew-packages | xargs brew install ) || return $?

	export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig
elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
	# We do not need to install in this script on Travis-CI Linux. The
	# packages are listed in .travis.yml
	true
fi

true
