#!/bin/bash

if [ "$TRAVIS_OS_NAME" == "osx" ]; then
	brew install cpanm || return $?

	# Create a local::lib
	cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

	# Override the rest of the default Perl Travis-CI commands because we are done.
	# Default for install: cpanm --quiet --installdeps --notest .
	function cpanm {
		eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
		echo "Installing deps"
		command cpanm --notest --installdeps .
		echo "Installing Alien::MuPDF"
		command cpanm -n Alien::MuPDF --verbose
	}

	# Default for script: make test (no M::B or EUMM)
	function make {
		export TEST_JOBS=4
		if [ "$#" == 1 ] && [ "$1" == "test" ]; then
			prove -j${TEST_JOBS} -lvr t
		fi
	}
elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
	eval $(curl https://travis-perl.github.io/init) --auto
fi
