# Generated by scan-prereqs-cpanfile. DO NOT EDIT!
requires 'Alien::MuPDF', '0.004';
requires 'Cairo';
requires 'Capture::Tiny';
requires 'Class::Method::Modifiers';
requires 'Glib';
requires 'Glib::Object::Introspection';
requires 'Glib::Object::Subclass';
requires 'Gtk3';
requires 'Modern::Perl';
requires 'Module::Util';
requires 'Moo';
requires 'Moo::Role';
requires 'Path::Tiny';
requires 'URI';
requires 'XML::Simple';
requires 'custom::failures';

on test => sub {
    requires 'Data::DPath';
    requires 'File::Temp';
    requires 'List::AllUtils';
    requires 'Test::MockModule';
    requires 'Test::MockObject';
    requires 'Test::Most';
    requires 'Try::Tiny';
    requires 'URI::file';
};
