---
abstract: 'A document reader written with GTK+.'
author:
  - 'Project Renard'
build_requires:
  File::Temp: '0'
  Log::Any: '0'
  Renard::Incunabula::Common::Error: '0'
  Renard::Incunabula::Devel::TestHelper: '0'
  Renard::Incunabula::Format::Cairo::Devel::TestHelper: '0'
  Renard::Incunabula::Outline: '0'
  Test::Exception: '0.43'
  Test::MockModule: '0'
  Test::MockObject: '0'
  Test::Most: '0'
  Test::Trap: '0'
  perl: '5.012'
  version: '0.77'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.012'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Renard-Curie
requires:
  Alien::MuPDF: '0.010'
  Bread::Board::Declare: '0'
  Cairo: '0'
  File::Basename: '0'
  File::Spec: '0'
  FindBin: '0'
  Getopt::Long::Descriptive: '0'
  Glib: '0'
  Glib::Object::Introspection: '0'
  Glib::Object::Subclass: '0'
  Gtk3: '0'
  Lingua::EN::Inflect: '0'
  List::AllUtils: '0'
  Log::Any::Adapter: '0'
  Log::Any::Adapter::Base: '0'
  Log::Any::Adapter::Util: '0'
  Modern::Perl: '0'
  Module::Util: '0'
  Moo: '2.001001'
  Moo::Role: '0'
  MooX::BuildArgs: '0'
  MooX::HandlesVia: '0'
  MooX::Lsub: '0'
  MooX::Role::CloneSet: '0'
  MooX::Role::CloneSet::BuildArgs: '0'
  MooX::Role::Logger: '0'
  MooX::Struct: '0'
  Moose: '0'
  POSIX: '0'
  Renard::Incunabula: '0.004'
  Renard::Incunabula::Common::Setup: '0'
  Renard::Incunabula::Common::Types: '0'
  Renard::Incunabula::Document: '0.004'
  Renard::Incunabula::Document::Types: '0'
  Renard::Incunabula::Format::Cairo: '0.004'
  Renard::Incunabula::Format::Cairo::Types: '0'
  Renard::Incunabula::Format::PDF: '0.004'
  Renard::Incunabula::Format::PDF::Document: '0'
  Renard::Incunabula::Format::PDF::InformationDictionary: '0'
  Renard::Incunabula::Frontend::Gtk3: '0.004'
  Renard::Incunabula::Frontend::Gtk3::Helper: '0'
  Renard::Incunabula::Frontend::Gtk3::Types: '0'
  Renard::Incunabula::MuPDF::mutool: '0.004'
  Test::Deep::NoTest: '0'
  URI: '0'
  URI::file: '0'
  constant: '0'
  custom::failures: '0'
  lib: '0'
  perl: '5.012'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  homepage: https://github.com/project-renard/curie
  repository: https://github.com/project-renard/curie.git
version: '0.004'
x_contributors:
  - 'Chirag <chiragghanshani@gmail.com>'
  - 'Helen Bach <haydeez.emma.roydz@gmail.com>'
  - 'Stanislav Yotov <yotov.st@gmail.com>'
  - 'Zakariyya Mughal <zaki.mughal@gmail.com>'
x_serialization_backend: 'YAML::Tiny version 1.70'
