#!/bin/sh

# Clean up local::lib environment output
# See example below
perl -I ~/perl5/lib/perl5 -Mlocal::lib  | perl -lpE 's|\\{4}|/|g; s|\\{2}|/|g; s|\+;|\+:|g; s|[cC]:|/c|g'

## Original output
# PATH="C:\\msys64\\home\\$USER/perl5\\bin${PATH:+;${PATH}}"; export PATH;
# PERL5LIB="C:\\msys64\\home\\$USER/perl5\\lib\\perl5${PERL5LIB:+;${PERL5LIB}}"; export PERL5LIB;
# PERL_LOCAL_LIB_ROOT="C:\\msys64\\home\\$USER/perl5${PERL_LOCAL_LIB_ROOT:+;${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
# PERL_MB_OPT="--install_base \"C:\\\\msys64\\\\home\\\\$USER/perl5\""; export PERL_MB_OPT;
# PERL_MM_OPT="INSTALL_BASE=C:\\\\msys64\\\\home\\\\$USER/perl5"; export PERL_MM_OPT;
#
## After using substitutions
# PATH="/c/msys64/home/$USER/perl5/bin${PATH:+:${PATH}}"; export PATH;
# PERL5LIB="/c/msys64/home/$USER/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
# PERL_LOCAL_LIB_ROOT="/c/msys64/home/$USER/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
# PERL_MB_OPT="--install_base \"/c/msys64/home/$USER/perl5\""; export PERL_MB_OPT;
# PERL_MM_OPT="INSTALL_BASE=/c/msys64/home/$USER/perl5"; export PERL_MM_OPT;
