use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007004
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib ) );
__DATA__
AccelMap
Adapter
Any
App
BUILDARGS
Bach
Chirag
Component
Container
Curie
DocumentModel
DragAndDrop
ExceptionHandler
FOREIGNBUILDARGS
FileChooser
ForDocument
Grid
Gtk
GtkPackType
HasParentMainWindow
Helen
LaxPageNumber
Log
LogWindow
MainWindow
MenuBar
Model
MuPDF
Mughal
Outline
PDF
PNG
PageCount
PageDrawingArea
PageNumber
Pageable
Percentage
Project
Renard
Renderable
RenderableDocumentModel
RenderablePageModel
Role
SizeRequest
Stanislav
Subview
SubviewPageable
UI
View
ViewManager
ViewModel
ViewOptions
Yotov
Zakariyya
Zoom
ZoomLevel
Zoomable
bin
chiragghanshani
curie
decrement
haydeez
initialises
keybindings
lib
mutool
revealer
scrollbar
submenu
subview
subwidgets
toplevel
yotov
zaki
